version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alex0942/foodgram-project-react_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media/
  frontend:
    image: alex0942/foodgram-project-react_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ./frontend/:/app/result_build/
      - static_volume:/frontend_static
  nginx:
    #image: alex0942/foodgram-project-react_nginx
    image: nginx:1.19.3
    env_file: .env
    restart: always
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles/
      - media:/media/
    ports:
      - 8000:80
